# Generated by Django 6.1.1 on 2026-10-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_serviceheartbeat_experiment_trashed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyversion',
            name='kind',
            field=models.CharField(default='python', max_length=12),
        ),
        migrations.AddField(
            model_name='strategyversion',
            name='recipe',
            field=models.JSONField(default=dict),
        ),
    ]
