# Generated by Django 6.1.1 on 2026-10-03 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('budget', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('observations', models.JSONField(default=list)),
                ('slot', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('target_month', models.CharField(blank=True, max_length=7)),
                ('targets', models.JSONField(default=dict)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='PaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(max_length=48, unique=True)),
                ('trading_date', models.DateField()),
                ('symbol', models.CharField(max_length=12)),
                ('side', models.CharField(max_length=4)),
                ('qty', models.PositiveIntegerField()),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('broker_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='intent', max_length=32)),
                ('filled_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('filled_price', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('error', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papersession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='papersession',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked', False)), fields=('slot',), name='one_unrevoked_paper_session'),
        ),
    ]
