# Generated by Django 6.1.1 on 2026-10-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_date', models.DateField()),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('inputs', models.JSONField()),
                ('targets', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papersession')),
            ],
        ),
        migrations.AddField(
            model_name='paperorder',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.paperdecision'),
        ),
    ]
