# Generated by Django 6.1.1 on 2026-10-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_paperdecision_paperorder_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_date', models.DateField()),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('inputs', models.JSONField()),
                ('targets', models.JSONField()),
                ('transfers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AccountOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(max_length=48, unique=True)),
                ('trading_date', models.DateField()),
                ('symbol', models.CharField(max_length=12)),
                ('side', models.CharField(max_length=4)),
                ('qty', models.PositiveIntegerField()),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocations', models.JSONField()),
                ('broker_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='intent', max_length=32)),
                ('filled_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('filled_price', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('applied_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('applied_notional', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('budget', models.DecimalField(decimal_places=2, default=10000, max_digits=18)),
                ('cap', models.FloatField(default=0.2)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='papersession',
            name='one_unrevoked_paper_session',
        ),
        migrations.AddField(
            model_name='papersession',
            name='cash',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='papersession',
            name='holdings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='papersession',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='papersession',
            name='last_cycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papersession',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='papersession',
            name='state',
            field=models.CharField(default='paused', max_length=16),
        ),
        migrations.AddField(
            model_name='accountorder',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.accountcycle'),
        ),
    ]
