# Generated by Django 6.1.1 on 2026-10-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_pause_existing_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountorder',
            name='applied_allocations',
            field=models.JSONField(default=dict),
        ),
    ]
