# Generated by Django 6.1.1 on 2026-10-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_accountorder_applied_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersession',
            name='desired_shares',
            field=models.JSONField(default=dict),
        ),
    ]
